allow-branch = ["main"]
publish = false
sign-commit = false
sign-tag = false
tag-name = "v{{version}}"
tag-message = "v{{version}}"
pre-release-commit-message = "chore(release): v{{version}}"
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "v{{version}}"]
push = true
push-remote = "origin"
verify = false
